# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LiveStreamingChatApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LiveStreamingChatApp
pod 'RNShare', :path => '../node_modules/react-native-share'
pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
pod 'react-native-camera', :path => '../node_modules/react-native-camera'
pod 'react-native-image-resizer', :path => 'react-native-image-resizer'
pod 'RNFS', :path => '../node_modules/react-native-fs'

end